# Generated by Django 4.2.11 on 2024-03-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='title',
        ),
    ]
